// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dcetsexykugrmfjixgal.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRjZXRzZXh5a3Vncm1maml4Z2FsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyMjkwNzYsImV4cCI6MjA2NDgwNTA3Nn0.w8PF2b0ejx_vG0tBWhfXS6QTu38fEPgi49VMmL7nerY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);